### ISSUE TITLE
testando linguagem Markdown

### ISSUE THREAD

**Issue by nunes2julia** [nunes2julia/Ola-Mundo#1]
test de linguagem markdown aqui.

**Comment by nunes2julia** [comment]
Aprendendo linguagem ~~Markdown~~ 

# aula de linguagem Markdown
***
podemos __*misturar*__ configuracoes
# Titulo
## titulo
### titulo

Lista numerada:

1. teste
1. teste2
   1. test2.1 (tres espacos vazios para fazer sub item)
1. teste3

Lista demarcada

* Teste
   *  Teste (espaco vazio)
   *  teste

Lista de tarefas:

- [x] Jogar
- [ ] gym
- [x] estudar
- [ ] remedio
- [x] dormir antes das 23h



-> notas <-
** / __  (negrito)  
* / _  (italico)
 ~~ (riscado)
# letras grandes

**Comment by nunes2julia** [comment]
[Acesse meu GitHub](https://github.com/nunes2julia)

**Comment by nunes2julia** [comment]
Num | Nome | Nota
---|---|---
1 | Julia | 10
2 | Riatla | 10
3 | Joao | 9.5
4 | Lucas | 7.5
5 | Cassiano | 3

**Comment by riatla** [comment]
Teste aula
- [ ] Dormir
- [x] jogar
- [ ] estudar
- [WorldBoss](https://www.wowhead.com/diablo-4/event-timers/world-bosses)

**Comment by nunes2julia** [comment]
Comando `document.getElementByld()` da linguagem JavaScript

```
num = int(input('Digite um valor: ')
if num % 2 == 0:
   print(f' O valor {num} e PAR')
else:
  print(f' O valor {num} e IMPAR')


```

**Comment by nunes2julia** [comment]
emoji 👍

**Comment by nunes2julia** [comment]
> java
> python
